version: '3.7'  
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    container_name: syk
    command:  bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && gunicorn mysite.wsgi — bind 0.0.0.0:8001"
    volumes:
      - ./publishing_platform:/publishing_platform
    depends_on:
      - db
    ports:
      - "8000:8000"
    tty: true

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: bktotient@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:80"
  nginx:
    image: nginx:latest
    ports:
       - 8088:80
    volumes:
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
       - web

volumes:
   postgres_data:

  
