version: '3.7'  
services:
  db:
    image: postgres:10.1-alpine
    environment:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: postgres
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
  
  web:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./publishing_platform/:/publishing_platform
      - static_volume:/publishing_platform/staticfiles
    depends_on:
      - db
    expose:
      - 8000
    networks:
      - backend
    tty: true

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: bktotient@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - backend
  nginx:
    build: ./nginx
    ports:
       - 8088:80
    volumes:
       - static_volume:/publishing_platform/staticfiles

    depends_on:
       - web
    networks:
       - backend
networks:
    backend:
      driver: bridge
volumes:
   postgres_data:
   static_volume:
  
